import React, { Component } from "react";
import Navbar from '../layout/Navbar'
import './pages.css';

export class Music extends Component {
  render() {
    return <div>
      <Navbar activeLink={"MUSIC"} />
      <div className="page">
        <div className="appear">
          <h1>THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE THIS IS THE MUSIC PAGE </h1>
        </div>
      </div>
    </div>;
  }
}

export default Music;