import React, { Component } from "react";
import Navbar from '../layout/Navbar'
import MediaQuery from 'react-responsive'
import './pages.css';

export class Software extends Component {

  render() {
    return <div>
      <Navbar activeLink={"SOFTWARE"} />
      <div className="page">
        <div className="appear">
          <h1>THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE THIS IS THE SOFTWARE PAGE </h1>
        </div>
      </div>
    </div>;
  }
}

export default Software;